# -*- coding: utf-8 -*-
"""NLP Fetch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kYJ-U2y6XuEXIMJiv3mPxLD3OFcEXzVI
"""

import os
import urllib.request
import pandas as pd
import sqlite3

# Define the URL of the file to download
url = "https://github.com/AmgadHasan/arabic-dialect-detection/raw/main/data/dialects_database.db"

# Define the local file path
folder_path = os.getcwd() + "/data/"
db_file_path = folder_path + "dialects_database.db"
# Check if the file exists
if not os.path.isfile(db_file_path):
    # If the file doesn't exist, download it from the URL
    print("Downloading file...")
    urllib.request.urlretrieve(url, db_file_path)
    print("File downloaded.")
else:
    print("File exists.")

# Connect to the database
conn = sqlite3.connect(db_file_path)

df = pd.read_sql_query("SELECT id_text.text, id_dialect.dialect FROM id_text INNER JOIN id_dialect ON id_text.id = id_dialect.id", conn)

# Print the resulting DataFrame
print(df)

# Close the connection
conn.close()

df.shape

df = df.rename(columns={'text': 'tweet', 'dialect':'label'})
csv_file_path = folder_path + "arabic_dialects.csv"

df.to_csv(csv_file_path)

print(df.memory_usage())
